### ISSUE TITLE
Example get to work

### ISSUE THREAD

**Issue by lepulent** [Mimiste/c2-scorm-plugin#1]
Hi, 
We are very intersted in get construct export an **scorm.zip** (we use moodle).
So, I was wondering what do I have in consideration to run your example.capx.
It shows "Scorm wasn´t able to initialise. Probably because the Scorm API was not found"
![screenshot_1](https://cloud.githubusercontent.com/assets/20479386/19706601/1c6acbbe-9ae9-11e6-8721-47aeb9ec9275.jpg)

Thanks, off course we are considering donation :+1:

**Comment by loic-martinez-freelance** [comment]
Hi,
I see you are running it on localhost:50000
I guess it's the construct 2 "run layout" preview. 
You can't run it this way because the plugin is searching for the scorm API that only a LMS can deliver. It mean that you have to export your construct 2 project as an HTML5 website, add your scorm manifest and publish the zip on moodle and then it should work (tested on Moodle 3.0.4) 

If you dont know what is a scorm manifest (the file name is imsmanifest.xml), I join to this comment the exported exemple with a base scorm 1.2 manifest. The zip is ready to be deployed on moodle.

[Scorm_C2_example.zip](https://github.com/Mimiste/c2-scorm-plugin/files/552636/Scorm_C2_example.zip)

(maybe I should include this exemple manifest in the capx)
